[package]
name = "mtproto"
version = "0.1.0"
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]

build = "build.rs"

[build-dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
quote = "0.3"

[dependencies]
byteorder = "1"
error-chain = "0.8"
